name: Keep Streamlit App Alive

on:
  # Run every 4 hours to prevent the Streamlit Community Cloud app from hibernating
  # Cron schedule: minute hour day month day_of_week
  # "0 */4 * * *" means: at minute 0 of every 4th hour (0:00, 4:00, 8:00, 12:00, 16:00, 20:00)
  schedule:
    - cron: '0 */4 * * *'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Streamlit App
      run: |
        # Make an HTTP GET request to the Streamlit app URL to keep it alive
        # Replace YOUR_STREAMLIT_APP_URL with your actual Streamlit Community Cloud app URL
        # Example: https://your-app-name-yourname.streamlit.app
        curl -f -s "YOUR_STREAMLIT_APP_URL" > /dev/null
        
        # Check if the request was successful
        if [ $? -eq 0 ]; then
          echo "✅ Successfully pinged the Streamlit app"
        else
          echo "❌ Failed to ping the Streamlit app"
          exit 1
        fi
      
    - name: Log timestamp
      run: echo "Keep-alive ping completed at $(date)"
