name: Keep Streamlit App Alive

on:
  # Run every 1 hour to prevent the Streamlit Community Cloud app from hibernating
  schedule:
    - cron: '0 * * * *'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Streamlit App with Retry Logic
      run: |
        APP_URL="https://diabetes-prediction-and-prevention-app.streamlit.app/"
        MAX_RETRIES=3
        RETRY_DELAY=10
        
        echo "🚀 Starting keep-alive ping for: $APP_URL"
        
        for i in $(seq 1 $MAX_RETRIES); do
          echo "📡 Attempt $i of $MAX_RETRIES..."
          
          # Make HTTP request with timeout and get response code
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 30 "$APP_URL" || echo "000")
          
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "✅ Success! App responded with HTTP $HTTP_CODE"
            echo "🎉 Streamlit app is alive and healthy"
            exit 0
          else
            echo "⚠️ Attempt $i failed with HTTP code: $HTTP_CODE"
            
            if [ $i -lt $MAX_RETRIES ]; then
              echo "⏳ Waiting ${RETRY_DELAY}s before retry..."
              sleep $RETRY_DELAY
            fi
          fi
        done
        
        echo "❌ All $MAX_RETRIES attempts failed"
        echo "🔍 Final HTTP code: $HTTP_CODE"
        exit 1
      
    - name: Log Completion
      if: always()
      run: |
        echo "📊 Keep-alive ping completed at $(date)"
        echo "🌍 Timezone: $(date +%Z)"
        echo "🕐 UTC Time: $(date -u)"